In [2]:
import numpy as np
from control.matlab import *
import scipy as sp
import matplotlib.pyplot as plt

10.3

In [3]:
#10.3_inner_1


#define constants 
s = tf([1,0], [1])
zsp = 2/(np.sqrt(13))
wsp = np.sqrt(13)
Kq = -24
Tt2 = 1.4

#Transfer Function
Htde = Kq*(1+Tt2*s)/(s*(s**2 + 2*zsp*wsp*s + wsp**2))

print(Htde)

%matplotlib qt

rlocus(-Htde)
plt.show()

gain = -0.443

print(damp((gain*Htde).feedback(1)))



   -33.6 s - 24
------------------
s^3 + 4 s^2 + 13 s

_____Eigenvalue______ Damping___ Frequency_
    -1.799    +4.817j     0.3499      5.142
    -1.799    -4.817j     0.3499      5.142
   -0.4021                     1     0.4021
(array([5.14178238, 5.14178238, 0.40214955]), array([0.34986413, 0.34986413, 1.        ]), array([-1.79892523+4.81682407j, -1.79892523-4.81682407j,
       -0.40214955+0.j        ]))


Clicked at     -1.818    -4.257j gain     0.2889 damp     0.3927


c:\Users\kaspe\anaconda3\lib\site-packages\control\rlocus.py:649: UserWarning: marker is redundantly defined by the 'marker' keyword argument and the fmt string "k." (-> marker='.'). The keyword argument will take precedence.
  ax_rlocus.plot(s.real, s.imag, 'k.', marker='s', markersize=8,


In [7]:
#10.3_inner_2

Hqde = Kq*(1+Tt2*s)/(s*s + 2*zsp*wsp*s + wsp*wsp)

print(Hqde)

rlocus(-Hqde)
plt.show()

gain2 = -0.08948

print(gain2)

damp((Hqde).feedback(gain2))


 -33.6 s - 24
--------------
s^2 + 4 s + 13

-0.08948
_____Eigenvalue______ Damping___ Frequency_
    -3.503    +1.695j     0.9001      3.892
    -3.503    -1.695j     0.9001      3.892


(array([3.8919815, 3.8919815]),
 array([0.9001235, 0.9001235]),
 array([-3.503264+1.69548263j, -3.503264-1.69548263j]))

In [11]:
#10.3_inner_3

#Constants
VTAS = 160
zsp = 2/(np.sqrt(13))
wsp = np.sqrt(13)
Kq = -24
Tt2 = 1.4

#Transfer Functions
Hq = Hqde
Htheta = Htde
Hgamma = Hq/(s*(1+Tt2*s))
Hh = VTAS*Hq/((s*s)*(1+Tt2*s))

#Big Array
Hall = tf([[Hq.num[0][0]], 
           [Htheta.num[0][0]],
           [Hgamma.num[0][0]],
           [Hh.num[0][0]]],
          [[Hq.den[0][0]], 
            [Htheta.den[0][0]],
            [Hgamma.den[0][0]],
            [Hh.den[0][0]]])

print(Hall)

#Input 1 is de
#Output 1 is q, pitch rate
#output 2 is theta, pitch attitude
#output 3 is gamma, flight angle
#output 4 is h, height

#State Space

sys1 = ss(Hall)

print(sys1)


Input 1 to output 1:
 -33.6 s - 24
--------------
s^2 + 4 s + 13

Input 1 to output 2:
   -33.6 s - 24
------------------
s^3 + 4 s^2 + 13 s

Input 1 to output 3:
           -33.6 s - 24
-----------------------------------
1.4 s^4 + 6.6 s^3 + 22.2 s^2 + 13 s

Input 1 to output 4:
           -5376 s - 3840
-------------------------------------
1.4 s^5 + 6.6 s^4 + 22.2 s^3 + 13 s^2

<LinearIOSystem>: sys[231]
Inputs (1): ['u[0]']
Outputs (4): ['y[0]', 'y[1]', 'y[2]', 'y[3]']
States (4): ['x[0]', 'x[1]', 'x[2]', 'x[3]']

A = [[-4.00000000e+00  1.30000000e+00  1.68291706e-16  4.25698344e-16]
     [-1.00000000e+01 -2.92133137e-16  1.96134988e-15 -2.90775104e-16]
     [ 0.00000000e+00  1.00000000e+00  1.44423686e-15 -1.03422604e-15]
     [ 0.00000000e+00  0.00000000e+00  1.00000000e+01 -1.77635684e-15]]

B = [[-10.]
     [  0.]
     [  0.]
     [  0.]]

C = [[ 3.36000000e+00 -2.40000000e-01  7.29387255e-16  1.60447947e-16]
     [ 4.51028104e-17 -3.36000000e-01 -2.40000000e-01  0.00000000e+0

In [19]:
#10.3_inner_4

Kr = -0.089

K_mat = np.matrix([Kr, 0, 0, 0])

sys2 = sys1.feedback(K_mat)

damp(sys2)

print(sys2)

t = np.arange(0, 20, 0.1)

y1, t = step(sys1, t, output = 0)
y2, t = step(sys2, t, output = 0)

print(y1.ravel()[-1])
print(y2.ravel()[-1])


_____Eigenvalue______ Damping___ Frequency_
    -3.495    +1.709j     0.8984      3.891
    -3.495    -1.709j     0.8984      3.891
 1.091e-15+1.164e-07j -9.374e-09  1.164e-07
 1.091e-15-1.164e-07j -9.374e-09  1.164e-07
<LinearICSystem>: sys[258]
Inputs (1): ['u[0]']
Outputs (4): ['y[0]', 'y[1]', 'y[2]', 'y[3]']
States (4): ['sys[231]_x[0]', 'sys[231]_x[1]', 'sys[231]_x[2]', 'sys[231]_x[3]']

A = [[-6.99040000e+00  1.51360000e+00 -4.80862952e-16  2.82899671e-16]
     [-1.00000000e+01 -2.92133137e-16  1.96134988e-15 -2.90775104e-16]
     [ 0.00000000e+00  1.00000000e+00  1.44423686e-15 -1.03422604e-15]
     [ 0.00000000e+00  0.00000000e+00  1.00000000e+01 -1.77635684e-15]]

B = [[-10.]
     [  0.]
     [  0.]
     [  0.]]

C = [[ 3.36000000e+00 -2.40000000e-01  7.29387255e-16  1.60447947e-16]
     [ 4.51028104e-17 -3.36000000e-01 -2.40000000e-01  0.00000000e+00]
     [ 5.37764278e-17  2.06929305e-17 -2.40000000e-01  5.55111512e-17]
     [ 0.00000000e+00 -8.88178420e-16 -8.88178420e-16 -

TypeError: stepinfo() got an unexpected keyword argument 'output'

In [25]:
#10.3_inner_5

Hth = tf(np.matrix([0, 1, 0, 0]) * sys2)

rlocus(-(Hth.minreal()), np.logspace(-3, 0, 300))
plt.show()

gain3 = -0.4737
damp(Hth.feedback(gain3))

_____Eigenvalue______ Damping___ Frequency_
    -3.295     +4.19j     0.6182      5.331
    -3.295     -4.19j     0.6182      5.331
   -0.4001                     1     0.4001


c:\Users\kaspe\anaconda3\lib\site-packages\scipy\signal\_filter_design.py:1746: BadCoefficients: Badly conditioned filter coefficients (numerator): the results may be meaningless
  warnings.warn("Badly conditioned filter coefficients (numerator): the "


(array([5.33062872, 5.33062872, 0.40009006]),
 array([0.61815503, 0.61815503, 1.        ]),
 array([-3.29515497+4.19017377j, -3.29515497-4.19017377j,
        -0.40009006+0.j        ]))

In [28]:
#10.3_inner_6

sys3 = (gain3*sys2).feedback(np.matrix([0, 1, 0, 0]))

print(sys3)

t = np.arange(0, 20, 0.1)

y3, t = step(sys3, t, output = 1)

f = y3[-1]
print(f)

print("Settling time sys 3 =", 
      t[np.logical_or(y3  > 1.05*f, y3 < 0.95*f)][-1])

h = 1/(1 + 2.5*s)
yh, t = step(h, t)
fh = yh[-1]

print("Settling time sys 1st order =", 
      t[np.logical_or(yh  > 1.05*fh, yh < 0.95*fh)][-1])


<LinearICSystem>: sys[382]
Inputs (1): ['u[0]']
Outputs (4): ['y[0]', 'y[1]', 'y[2]', 'y[3]']
States (4): ['sys[379]_sys[258]_sys[231]_x[0]', 'sys[379]_sys[258]_sys[231]_x[1]', 'sys[379]_sys[258]_sys[231]_x[2]', 'sys[379]_sys[258]_sys[231]_x[3]']

A = [[-6.99040000e+00  3.10523200e+00  1.13688000e+00  2.82899671e-16]
     [-1.00000000e+01 -2.92133137e-16  1.96134988e-15 -2.90775104e-16]
     [ 0.00000000e+00  1.00000000e+00  1.44423686e-15 -1.03422604e-15]
     [ 0.00000000e+00  0.00000000e+00  1.00000000e+01 -1.77635684e-15]]

B = [[-10.]
     [  0.]
     [  0.]
     [  0.]]

C = [[-1.59163200e+00  1.13688000e-01 -3.45510743e-16 -7.60041923e-17]
     [-2.13652013e-17  1.59163200e-01  1.13688000e-01  0.00000000e+00]
     [-2.54738938e-17 -9.80224120e-18  1.13688000e-01 -2.62956323e-17]
     [ 0.00000000e+00  4.20730117e-16  4.20730117e-16  1.81900800e+00]]

D = [[0.]
     [0.]
     [0.]
     [0.]]

0.9998320537949117
Settling time sys 3 = 5.6000000000000005
Settling time sys 1st order 

10.4

In [29]:
#10.4_altitude_1

#use the same sys3 and t

y_theta, t = step(sys3, t, output = 2)

f = y_theta[-1]
print(f)

print("Settling Time =", 
      t[np.logical_or(y_theta > 1.05*f, y_theta < 0.95*f)][-1])

0.9996181946765208
Settling Time = 7.6000000000000005


In [37]:
H = tf(sp.matrix([[0, 0, 0, 1]])*sys3).minreal()
# the removal process is slightly different here, we just remove the small leading terms of the numerator vector
H.num[0][0] = H.num[0][0][-1:]
print(H)

rlocus(H)
plt.show()

gain4 = 0.0012
print(gain4)

damp(((H*gain4).feedback(1)))

sys4 = (H*gain4).feedback(1)

y4, t = step(sys4, t)

f = y4[-1]
print(f)

print("Settling Time =", 
      t[np.logical_or(y4 > 1.05, y4 < 0.95)][-1])



                     1819
-----------------------------------------------
s^4 + 6.99 s^3 + 31.05 s^2 + 11.37 s + 3.32e-13

0.0012
_____Eigenvalue______ Damping___ Frequency_
    -3.304    +4.187j     0.6195      5.334
    -3.304    -4.187j     0.6195      5.334
   -0.1909   +0.2007j     0.6891      0.277
   -0.1909   -0.2007j     0.6891      0.277
1.0322914290876972
Settling Time = 16.3
