In [4]:
#imports
from control.matlab import *
import numpy as np
import matplotlib.pyplot as plt

State Space to Transfer Function

In [5]:
# create a state space system
a = np.matrix(""" 0       1      0   ;
                 -0.0071 -0.111  0.12;
                  0       0.07  -0.3""")
b = np.matrix(""" 0 ;    -0.095; 0.072""")
c = np.matrix(""" 1       0     0    """)
d = np.matrix(""" 0     """)
sys = ss(a, b, c, d)

#then simply convert to transfer functions
h = tf(sys)
print(h)


        -0.095 s - 0.01986
-----------------------------------
s^3 + 0.411 s^2 + 0.032 s + 0.00213



In [6]:
#now create a random state space system with rss
sys = rss(3,2,3)
#https://python-control.readthedocs.io/en/latest/generated/control.matlab.rss.html

print(sys)

sys_tf = tf(sys)

print(sys_tf)



<LinearIOSystem>: sys[4]
Inputs (3): ['u[0]', 'u[1]', 'u[2]']
Outputs (2): ['y[0]', 'y[1]']
States (3): ['x[0]', 'x[1]', 'x[2]']

A = [[ -1.73916078   1.38264082  -0.9781527 ]
     [  5.0441428   15.77137927 -12.16859638]
     [ 10.39798276  21.26190408 -16.20466989]]

B = [[-0.15785262 -1.01000925  0.75324424]
     [ 0.19297123  0.27935514 -1.40673876]
     [ 0.20118671  2.05859797 -1.5881055 ]]

C = [[-1.10097234  1.50561728 -2.1824251 ]
     [ 0.09650343  0.          1.3188358 ]]

D = [[-0.         -0.61483717  0.        ]
     [-0.         -0.          1.06376596]]


Input 1 to output 1:
  0.02526 s^2 + 1.116 s - 11.67
---------------------------------
s^3 + 2.172 s^2 + 7.108 s + 11.92

Input 1 to output 2:
  0.2501 s^2 - 0.4766 s + 15.71
---------------------------------
s^3 + 2.172 s^2 + 7.108 s + 11.92

Input 2 to output 1:
-0.6148 s^3 - 4.296 s^2 + 33.06 s + 0.3937
------------------------------------------
    s^3 + 2.172 s^2 + 7.108 s + 11.92

Input 2 to output 2:
   2.617 s^

What the tf conversion gives is an array:

Each row is an output
Each column is an input

So at 2,1, you have input 1 to output 2

In [9]:
h = tf(sys)

# select one of the transfer functions
h11 = tf(h.num[0][0], h.den[0][0])
print(h11)


  0.02526 s^2 + 1.116 s - 11.67
---------------------------------
s^3 + 2.172 s^2 + 7.108 s + 11.92



Transfer Function to State Space

In [10]:
# invent a transfer function
s = tf([1, 0], [1])
h = (1 + 2*s)/(s*(s ** 2 + 0.5 *s + 4))
# convert to state-space
sys = ss(h)
print(sys)

<LinearIOSystem>: sys[26]
Inputs (1): ['u[0]']
Outputs (1): ['y[0]']
States (3): ['x[0]', 'x[1]', 'x[2]']

A = [[-5.00000000e-01  4.00000000e+00  7.77156117e-16]
     [-1.00000000e+00  1.30424808e-16 -6.39685599e-16]
     [ 0.00000000e+00  1.00000000e+00 -8.32667268e-17]]

B = [[-1.]
     [ 0.]
     [ 0.]]

C = [[0. 2. 1.]]

D = [[0.]]



In [13]:
# a multi-dimensional transfer function needs to be entered with num and
# den arrays in Python
H = tf( [ [h.num[0][0]], [(h*s).num[0][0]] ], 
        [ [h.den[0][0]], [(h*s).den[0][0]] ])
print(H)
print(ss(H))


Input 1 to output 1:
      2 s + 1
-------------------
s^3 + 0.5 s^2 + 4 s

Input 1 to output 2:
     2 s^2 + s
-------------------
s^3 + 0.5 s^2 + 4 s

<LinearIOSystem>: sys[37]
Inputs (1): ['u[0]']
Outputs (2): ['y[0]', 'y[1]']
States (3): ['x[0]', 'x[1]', 'x[2]']

A = [[-5.00000000e-01  4.00000000e+00  3.33066907e-16]
     [-1.00000000e+00 -1.73347749e-15 -4.48355394e-17]
     [ 0.00000000e+00  1.00000000e+00 -2.77555756e-17]]

B = [[-1.]
     [ 0.]
     [ 0.]]

C = [[ 0.00000000e+00  2.00000000e+00  1.00000000e+00]
     [-2.00000000e+00  1.00000000e+00  5.82867088e-16]]

D = [[0.]
     [0.]]

