In [11]:
%matplotlib qt
from control.matlab import *
import matplotlib.pyplot as plt
from math import sqrt
import scipy as sp


In [12]:
# setup
Kq = -24
wsp = sqrt(13)
zsp = 2/sqrt(13)
Tt2 = 1.4

s = tf([1, 0], [1])
Hqde = Kq*(1+Tt2*s)/(s**2 + 2*zsp*wsp*s + wsp**2)

In [14]:
#Rlocus Plot

plt.figure()
# zoom in near the origin to get a better view
rlocus(-Hqde) #Make sure you input the open loop transfer function here

# add a damping line of zeta = 0.9, if this puzzles you, check the slides of lecture 7
# the length 4 is chosen to be long enough to cross the root-locus branch, simply 
# look at the plot first and estimate something appropriate
zeta = 0.9
plt.plot([0, -zeta*4], [0, 4*sqrt(1-zeta**2)])

plt.show()

Clicked at     -1.798   +0.8003j gain     0.1451 damp     0.9136


In [ ]:
#Sisotool
plt.figure()
sisotool(Hqde) #root locus, bode plots, and step response all in one windown
plt.show()

In [15]:
# as always, verify the found gain
Kr = -0.08948
Hc = Hqde.feedback(Kr)
damp(Hc)

_____Eigenvalue______ Damping___ Frequency_
    -3.503    +1.695j     0.9001      3.892
    -3.503    -1.695j     0.9001      3.892


(array([3.8919815, 3.8919815]),
 array([0.9001235, 0.9001235]),
 array([-3.503264+1.69548263j, -3.503264-1.69548263j]))

In [20]:
#Bode Plots
plt.figure()
bode(Hqde)  #This also returns, magnitude, phase and omega in arrays
plt.show()

print(margin(Hqde)) #Note that the gain margin is not given in dB:
gm, pm, wg, wp = margin(Hqde)
print(wp, pm, 20*sp.log10(gm))

mag, phase, w = bode(Hqde)

#Find Resonance peak in db
print("resonance", 20*sp.log10(mag.max()))

#Find Bandwidth
print("bandiwdth", w[mag > 10**(-3./20)][-1]/(2*sp.pi))




(0.5416666666666666, -84.37668909441766, 0.0, 33.753773588990825)
33.753773588990825 -84.37668909441766 -5.325357788095387
resonance 18.654680672566236
bandiwdth 7.542161146039559


C:\Users\kaspe\AppData\Local\Temp\ipykernel_6360\956253090.py:8: DeprecationWarning: scipy.log10 is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.log10 instead
  print(wp, pm, 20*sp.log10(gm))
C:\Users\kaspe\AppData\Local\Temp\ipykernel_6360\956253090.py:13: DeprecationWarning: scipy.log10 is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.log10 instead
  print("resonance", 20*sp.log10(mag.max()))


In [18]:
help(margin)

Help on function margin in module control.margins:

margin(*args)
    margin(sysdata)
    
    Calculate gain and phase margins and associated crossover frequencies
    
    Parameters
    ----------
    sysdata : LTI system or (mag, phase, omega) sequence
        sys : StateSpace or TransferFunction
            Linear SISO system representing the loop transfer function
        mag, phase, omega : sequence of array_like
            Input magnitude, phase (in deg.), and frequencies (rad/sec) from
            bode frequency response data
    
    Returns
    -------
    gm : float
        Gain margin
    pm : float
        Phase margin (in degrees)
    wcg : float or array_like
        Crossover frequency associated with gain margin (phase crossover
        frequency), where phase crosses below -180 degrees.
    wcp : float or array_like
        Crossover frequency associated with phase margin (gain crossover
        frequency), where gain crosses below 1.
    
    Margins are calculated

In [21]:
#Polar plots

plt.figure()
nyquist(Hqde)
plt.show()  

#or

[re, im] = nyquist(Hqde)
plt.figure()
plt.plot(squeeze(re), squeeze(im))
plt.show()

ValueError: array of sample points is empty